---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: set hostname
  hostname:
    name: "{{ new_hostname }}"

- name: download k3s binary
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v1.21.0%2Bk3s1/k3s
    dest: /usr/local/bin/k3s
    mode: '0777'
    checksum: md5:cfa46e4e202937d785850c860da024b1
  notify: start k3s service

- name: Copy k3s.service file
  copy:
    src: k3s.service
    dest: /etc/systemd/system/k3s.service
    mode: '0644'
  notify: start k3s service

- name: Copy k3s config file
  template:
      src: config.yaml.j2
      dest: /var/lib/rancher/k3s/config.yaml
      mode: '0644'
  notify: start k3s service